name: e_shop_flutter
description: EShop.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <34.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ARCH
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0  
  get_it: ^7.2.0 
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.2
  path: ^1.8.3
  shared_preferences: ^2.0.18
  equatable: ^2.0.5

  # OTHER
  grouped_list: ^5.1.2
  intl: ^0.18.0
  sqlite3_flutter_libs: ^0.5.13
  path_provider: ^2.0.13
  cupertino_icons: ^1.0.5
  drift: ^2.5.0
  go_router_flow: ^6.2.0
  
  
dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.5.2
  freezed: ^2.2.0
  json_serializable: ^6.6.1

flutter:
  assets:
    - assets/ic/

  uses-material-design: true
  